# Generated by Django 5.0.6 on 2024-06-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Especie',
        ),
        migrations.AddField(
            model_name='mascota',
            name='caracteristicas_distintivas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='email_dueno',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='especie',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mascotas/'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='nombre_dueno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mascota',
            name='numero_celular_dueno',
            field=models.CharField(default='+569', max_length=8),
        ),
        migrations.AddField(
            model_name='mascota',
            name='pelaje_color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mascota',
            name='pelaje_tipo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tamaño',
            field=models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=6),
        ),
        migrations.DeleteModel(
            name='FichaMedica',
        ),
    ]
