# Generated by Django 5.0.6 on 2024-06-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_especie_mascota_caracteristicas_distintivas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='numero_celular_dueno',
            field=models.CharField(default='+569', editable=False, max_length=14),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='pelaje_tipo',
            field=models.CharField(choices=[('pelilargo', 'Pelilargo'), ('pelicorto', 'Pelicorto')], default='', max_length=100),
        ),
    ]
