# Generated by Django 5.0.6 on 2024-06-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mascota_numero_celular_dueno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='numero_celular_dueno',
            field=models.CharField(default='+569', max_length=8),
        ),
    ]
