# Generated by Django 5.0.6 on 2024-06-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_mascota_numero_celular_dueno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='pelaje_tipo',
            field=models.CharField(choices=[('otro', 'Otro'), ('pelilargo', 'Pelilargo'), ('pelicorto', 'Pelicorto')], default='', max_length=100),
        ),
    ]
